// First-system mechanical envelopes.
// Generated by generate_envelopes.py — numbers cited in docs/oam_mechanical_envelope_v1.md
// NOT a fabrication or cooling-qualification model.

oam_w = 102.0;
oam_l = 165.0;
oam_t = 3.2;
koz_w = 103.0;
koz_l = 166.0;
stack_h = 5.0;
two_w = 2*koz_w;
eight_w = 4*koz_w;
eight_l = 2*koz_l;
host_w = 330.2;
host_l = 304.8;
cooler_w = 150.0;
cooler_d = 78.0;
cooler_h = 165.0;
cooling_planning_h = 100.0; // UNKNOWN real HS height

module oam_pcb() color([0.55,0.75,0.45]) cube([oam_w, oam_l, oam_t]);
module koz() color([0.2,0.4,0.8,0.25]) cube([koz_w, koz_l, 0.4]);

module two_gpu() {
    for (i=[0:1]) translate([i*koz_w, 0, 0]) {
        koz();
        translate([0.5, 0.5, stack_h]) oam_pcb();
    }
    color([1,0.6,0.1,0.2]) translate([0,0,stack_h+oam_t])
        cube([two_w, koz_l, cooling_planning_h]);
}

module eight_reserve() color([1,0.5,0,0.12]) cube([eight_w, eight_l, 0.4]);

module host() {
    color([0.6,0.3,0.7]) cube([host_w, host_l, 2.4]);
    // CPU-to-CPU pitch UNKNOWN — coolers shown as placeholders, not socket-accurate
    color([0.45,0.15,0.6,0.7]) translate([20, 40, 2.4]) cube([cooler_w, cooler_d, cooler_h]);
    color([0.45,0.15,0.6,0.7]) translate([180, 40, 2.4]) cube([cooler_w, cooler_d, cooler_h]);
}

eight_reserve();
two_gpu();
translate([eight_w + 30, 0, 0]) host();
